ALTER TABLE sales ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS cancel_reason VARCHAR(255);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS cfdi_uuid VARCHAR(255);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS cfdi_status VARCHAR(50);